addons:
  apt:
    packages:
    - libgeos-dev
    - libproj-dev
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - rbx-2
before_install:
  - ll /usr/lib/libgeos*
  # - sudo ln -s /usr/lib/libgeos-*.so /usr/lib/libgeos.so
